version: "3"

services:
  web:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=posse
    ports:
      - 3306:3306